---
title: "4--1"
author: "Bo"
date: "2025-07-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
library(AER)
```


```{r pressure, echo=FALSE}
mydata1 = read.csv("Education_data.csv")
head(mydata1)
```

```{r}
ols.res = lm(log(wage)~educ + exper + I(exper^2), data = mydata1)
summary(ols.res)
```


```{r}
stage1.1 = lm(educ~fatheduc+motheduc+nearc4+exper + I(exper^2), data = mydata1)
summary(stage1.1)
```


```{r}
stage2.1 = lm(log(wage)~fitted(stage1) + exper + I(exper^2), data = mydata1)
summary(stage2.1)
```


```{r}
stage1 = lm(educ~nearc4+exper + I(exper^2), data = mydata1)
summary(stage1)
```

```{r}
stage2 = lm(log(wage)~fitted(stage1) + exper + I(exper^2), data = mydata1)
summary(stage2)
```

```{r}
TSLS.res = ivreg(log(wage)~educ + exper + I(exper^2)|nearc4 + exper + I(exper^2), data = mydata1 )
summary(TSLS.res)
```

```{r}
cbind(coef(ols.res), coef(TSLS.res))
```















```{r}
mydata = read.csv("ShoppingVisits.csv")
head(mydata)
```

```{r}
km.res.ns = kmeans(mydata, 3, nstart = 20)
km.res.ns

plot(mydata, col=km.res.ns$cluster, pch=20, main="k means with 3 clusters without scaling")

```



```{r}
mydata.sc = scale(mydata)

```


```{r}
km.res.3 = kmeans(mydata.sc, 3, nstart = 20)

plot(mydata, col=km.res.3$cluster, pch=20, main="k means with 3 clusters with scaling")

```



```{r}
par(mfrow=c(1,2))
plot(mydata, col=km.res.ns$cluster, pch=20, main="k means with 3 clusters without scaling")
plot(mydata, col=km.res.3$cluster, pch=20, main="k means with 3 clusters with scaling")

```


```{r}
km.res.2 = kmeans(mydata.sc, 2, nstart = 20)
plot(mydata, col=km.res.2$cluster, pch=20, main="k means with 2 clusters with scaling")

km.res.4 = kmeans(mydata.sc, 4, nstart = 20)
plot(mydata, col=km.res.4$cluster, pch=20, main="k means with 4 clusters with scaling")

km.res.5 = kmeans(mydata.sc, 5, nstart = 20)
plot(mydata, col=km.res.5$cluster, pch=20, main="k means with 5 clusters with scaling")

```



```{r}
par(mfrow=c(2,2))
plot(mydata, col=km.res.2$cluster, pch=20, main="k means with 2 clusters with scaling")
plot(mydata, col=km.res.3$cluster, pch=20, main="k means with 3 clusters with scaling")
plot(mydata, col=km.res.4$cluster, pch=20, main="k means with 4 clusters with scaling")
plot(mydata, col=km.res.5$cluster, pch=20, main="k means with 5 clusters with scaling")

```

```{r}

ss1 = km.res.2$totss
ss2 = km.res.2$tot.withinss
ss3 = km.res.3$tot.withinss
ss4 = km.res.4$tot.withinss
ss5 = km.res.5$tot.withinss

ss.vec = c(ss1, ss2, ss3, ss4, ss5)

par(mfrow=c(1,1))

plot(ss.vec, type = "b", xlab="number of cluster", ylab = "total within-cluster ss")

```


```{r}
hc.res.average = hclust(dist(mydata.sc), method = "average")
plot(hc.res.average, cex=0.5, main = "dendrogram (average linkage)", xlab="", ylab="", sub="")
abline(h= 1.75, col="red", lty=2)
```

```{r}
par(mfrow=c(1,2))
plot(mydata, col=km.res.3$cluster, pch=20, main="k means with 3 clusters with scaling")
plot(mydata, col=cutree(hc.res.average, k=3), pch=20, main="hierarchcial clustering (average linkage)")
```

```{r}





```











