---
title: "5-2"
author: "Bo"
date: "2025-07-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
library(neuralnet)
```


```{r pressure, echo=FALSE}
mydata=read.csv("Smarket.csv")
mydata
```


```{r}
mydata = mydata[, -c(1,8)]

mydata[, -7] = scale(mydata[, -7])

```


```{r}
n.train = floor(nrow(mydata) * 0.8)
set.seed(1000)
ind.train = sample(1:nrow(mydata), n.train)
data.train = mydata[ind.train, ]
data.test = mydata[-ind.train, ]
```


```{r}
nn = neuralnet(Up~Lag1+Lag2, data = data.train, hidden = 2, linear.output = FALSE)
load("Smarket_nn1.Rda")
```


```{r}
plot(nn, rep = "best")
nn$weights
```


```{r}
data.test[1,]

```


```{r}
s1 = (-1.5526810) + (-0.4006151)*(-0.5516457	) + (0.3979986)*(0.9047775)
s1 = exp(s1)/(1+exp(s1))
s1
```

```{r}
s2 = (-20.092955) + (1.325688)*(-0.5516457	) + (33.606746)*(0.9047775)
s2 = exp(s2)/(1+exp(s2))
s2
```

```{r}
p1 = (-0.2670554) + (2.5133068)*s1 + (-0.7918837)*s2
p1 =  exp(p1)/(1+exp(p1))
p1
```


```{r}
compute(nn, data.test[1, ])
```


```{r}

nnn = neuralnet(Up~., data = data.train, hidden=c(4,2), linear.output = FALSE)
load("Smarket_nn2.Rda")

```


```{r}
plot(nnn, rep="best")
nnn$weights

```


```{r}
pred = compute(nnn, data.test)
pred$net.result
```


```{r}
pred.class = rep(FALSE, nrow(data.test))
pred.class[pred$net.result > 0.5] = TRUE
```


```{r}
confusion = table(pred.class, data.test$Up)
confusion
```

```{r}
sum(diag(confusion)) / sum(confusion)
```

```{r}
log.res = glm(Up~., data = data.train, family = binomial(link = logit))
summary(log.res)
```

```{r}
logit.pred.prob = predict(log.res, data.test, type="response")
logit.pred = rep(FALSE, nrow(data.test))
logit.pred[logit.pred.prob > 0.5] = TRUE

```


```{r}
confusion.logit = table(logit.pred, data.test$Up)
confusion.logit
```

```{r}
sum(diag(confusion.logit)) / sum(confusion.logit)
```

```{r}

```






























































